// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	perun "github.com/hyperledger-labs/perun-node"
	mock "github.com/stretchr/testify/mock"
)

// ChProposalNotifier is an autogenerated mock type for the ChProposalNotifier type
type ChProposalNotifier struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ChProposalNotifier) Execute(_a0 perun.ChProposalNotif) {
	_m.Called(_a0)
}
