version: 2.1

executors:
  perun-node-executor:
    docker:
      - image: cimg/go:1.14.1-node
    environment:
      RESULTS: /tmp/results
      ARTIFACTS: /tmp/artifacts
      TERM: xterm
    working_directory: ~/perun-node

commands:
  checkout-code:
    steps:
      - checkout
      - run:
          name: Check if go.mod requires update
          command: go list -mod=readonly ./...

  make-results-artifacts-dir:
    steps:
      - run: mkdir -p $RESULTS && ls -l /tmp
      - run: mkdir -p $ARTIFACTS && ls -l /tmp

  upload-results-artifacts:
    steps:
      - store_test_results:
          path: /tmp/results
      - store_artifacts:
          path: /tmp/artifacts

  install-ganache-cli:
      steps:
        - run: sudo npm install -g ganache-cli

  run-ganache-cli:
      steps:
        - run:
            command: ganache-cli -b 1 --account="0x1fedd636dbc7e8d41a0622a2040b86fea8842cef9d4aa4c582aad00465b7acff,100000000000000000000" --account="0xb0309c60b4622d3071fad3e16c2ce4d0b1e7758316c187754f4dd0cfb44ceb33,100000000000000000000"
            background: true

  wait-until-ganache-cli-is-running:
      steps:
        - run: timeout 15 bash -c 'until nc -z 127.0.0.1 8545; do sleep 1; done'

  install-txt-to-html-coverter-aha:
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install aha

jobs:

  lint:
    executor: perun-node-executor
    steps:
      - checkout-code
      - make-results-artifacts-dir
      - run:
          name: Install linter
          command: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.28.2
      - install-txt-to-html-coverter-aha
      - run:
          name: Run linter
          command: golangci-lint run --out-format='junit-xml' -v ./... | tee ${RESULTS}/lint.xml
      - run:
          name: Check copyright notice
          command: .scripts/copyright_notice_check.sh | tee >(aha --title "Check for Copyright Notice" --pink > ${ARTIFACTS}/copyright_notice_check.html)
          when: always
      - upload-results-artifacts


  unit_test:
    executor: perun-node-executor
    steps:
      - checkout-code
      - make-results-artifacts-dir
      - run:
          name: Run unit tests
          command: gotestsum --junitfile ${RESULTS}/unit-tests.xml --format=short-verbose -- -coverprofile=c.out ./...
      - run:
          name: Generate coverage report
          command: go tool cover -html=c.out -o ${ARTIFACTS}/unit_test_coverage.html
          when: always
      - uploakd-results-artifacts

  integration-tests:
    executor: perun-node-executor
    steps:
      - checkout-code
      - make-results-artifacts-dir
      - install-ganache-cli
      - run-ganache-cli
      - wait-until-ganache-cli-is-running
      - run: echo "ganache-cli-running"
      - run:
          name: Run integration tests for all but session, api/grpc.
          command: gotestsum --junitfile ${RESULTS}/unit-tests.xml --format=short-verbose -- -tags=integration -coverprofile=c.out -p 1 ./...
      - run:
          name: Generate coverage report
          command: go tool cover -html=c.out -o ${ARTIFACTS}/unit_test_coverage.html
          when: always
      - upload-results-artifacts

workflows:
  build-lint-test:
    jobs:
      # - lint
      # - unit_test
      - integration-tests
